
export const USERINFO = 'USERINFO'
export const LOADINGSTATUS = 'LOADINGSTATUS'
export const LOADINGTXT = 'LOADINGTXT'
export const PULLUPSTATUS = 'PULLUPSTATUS'
export const PULLDOWNSTATUS = 'PULLDOWNSTATUS'